import {average,DAY} from './math.mjs';
const $=s=>document.querySelector(s),svg=$('#chart'),NS='http://www.w3.org/2000/svg';
let data,lo,hi,geometry,visible=new Set(),drag=null,activePeriod='ytd',selectedDate=null;
const dateFmt=new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'});
const shortFmt=new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'short',timeZone:'UTC'});
const num=v=>v==null?'—':v.toLocaleString('de-DE',{maximumFractionDigits:1})+' %';
const iso=t=>new Date(t).toISOString().slice(0,10);
function el(tag,attrs={},text){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!=null)n.textContent=text;return n;}
function layers(){return [['raw',1,''],['sma7',7,''],['sma14',14,'6 4']].filter(([id])=>$('#'+id).checked);}
function setPeriod(period){activePeriod=period;const end=Date.parse(data.latestDate),start=Date.parse(data.points[0].date);hi=end;lo=period==='all'?start:period==='ytd'?Math.max(start,Date.parse(`${new Date(end).getUTCFullYear()}-01-01`)):Math.max(start,end-(Number(period)-1)*DAY);render();}
function clamp(){const min=Date.parse(data.points[0].date),max=Date.parse(data.latestDate);lo=Math.max(min,Math.min(lo,max));hi=Math.max(lo,Math.min(hi,max));}
function render(){if(!data)return;clamp();svg.replaceChildren();$('#tooltip').hidden=true;$('#from').value=iso(lo);$('#to').value=iso(hi);for(const n of $('#periods').children)n.classList.toggle('active',n.dataset.days===activePeriod);$('#rangeLabel').textContent=`${dateFmt.format(lo)} – ${dateFmt.format(hi)}`;
 const w=svg.clientWidth,h=svg.clientHeight,L=w<500?38:46,R=15,T=20,B=34,W=w-L-R,H=h-T-B,span=Math.max(DAY,hi-lo);const x=t=>L+(t-lo)/span*W,y=v=>T+(100-v)/100*H;geometry={w,h,L,R,T,B,W,H,x,y,span};
 svg.append(el('title',{},'Anteil der Coins mit höherer Tagesrendite als Bitcoin nach Marktkapitalisierung'));
 const defs=el('defs'),clip=el('clipPath',{id:'plotClip'});clip.append(el('rect',{x:L,y:T,width:W,height:H}));defs.append(clip);svg.append(defs);
 for(let v=0;v<=100;v+=10){svg.append(el('line',{x1:L,x2:w-R,y1:y(v),y2:y(v),stroke:v===50?'#68808b':'#273b46','stroke-width':v===50?1.1:.7,'stroke-dasharray':v===50?'4 5':''}));svg.append(el('text',{x:L-9,y:y(v)+4,'text-anchor':'end',fill:'#90a7b4','font-size':11},v));}
 const ticks=w<500?3:Math.min(9,Math.floor(W/100));for(let i=0;i<ticks;i++){const t=lo+span*i/(ticks-1);svg.append(el('text',{x:x(t),y:h-8,'text-anchor':i===0?'start':i===ticks-1?'end':'middle',fill:'#90a7b4','font-size':11},shortFmt.format(t)));}
 const plot=el('g',{'clip-path':'url(#plotClip)'});svg.append(plot);let lineCount=0;
 const modes=layers();for(const g of data.groups){if(!visible.has(g.id))continue;for(const[id,n,dash]of modes){const vals=n===1?data.points.map(p=>p.groups[g.id]?.value):average(data.points,g.id,n);let d='',previousT=null;for(let i=0;i<data.points.length;i++){const t=Date.parse(data.points[i].date),v=vals[i];if(v==null){previousT=null;continue;}const move=previousT==null||t-previousT!==DAY;d+=`${move?'M':'L'}${x(t).toFixed(2)},${y(v).toFixed(2)}`;if(t>=lo&&t<=hi)lineCount++;previousT=t;}plot.append(el('path',{d,fill:'none',stroke:g.color,'stroke-width':n===1?1.3:2.3,opacity:n===1&&modes.length>1?.3:.95,'stroke-dasharray':dash,'stroke-linejoin':'round','stroke-linecap':'round'}));}}
 const observed=data.points.find(p=>p.mode==='observed');if(observed&&Date.parse(observed.date)>=lo&&Date.parse(observed.date)<=hi){const xx=x(Date.parse(observed.date));plot.append(el('line',{x1:xx,x2:xx,y1:T,y2:T+H,stroke:'#bec8c9','stroke-dasharray':'3 4'}));}
 svg.append(el('line',{id:'guide',y1:T,y2:T+H,stroke:'#829da9','stroke-width':1,visibility:'hidden'}));
 const rect=el('rect',{id:'hit',x:L,y:T,width:W,height:H,fill:'transparent'});svg.append(rect);
 $('#empty').hidden=lineCount>0;$('#empty').textContent=modes.length===0?'Bitte mindestens eine Darstellung auswählen.':visible.size===0?'Bitte mindestens eine Ranggruppe auswählen.':'Für diesen Zeitraum liegen noch keine vollständigen Werte vor.';
 const rec=data.points.some(p=>Date.parse(p.date)>=lo&&Date.parse(p.date)<=hi&&p.mode==='reconstructed');$('#notice').textContent=rec?'Historische Rekonstruktion: Die rückwirkenden Werte verwenden die Coin-Auswahl und Ranggruppen vom '+dateFmt.format(Date.parse(data.bootstrapDate))+'. Frühere Rangwechsel und ausgeschiedene Coins sind nicht enthalten. Neue tägliche Beobachtungen werden mit ihrer jeweiligen Zusammensetzung gespeichert.':'Gespeicherte tägliche Beobachtungen mit der jeweils beim Abruf erfassten Zusammensetzung. Fehlende Preise werden aus dem Nenner ausgeschlossen.';
}
function inspect(event){if(!geometry||!data)return;const rect=svg.getBoundingClientRect(),mx=event.clientX-rect.left;const t=lo+Math.max(0,Math.min(geometry.W,mx-geometry.L))/geometry.W*geometry.span;const p=data.points.reduce((a,b)=>Math.abs(Date.parse(a.date)-t)<Math.abs(Date.parse(b.date)-t)?a:b);selectedDate=p.date;const xx=geometry.x(Date.parse(p.date));const guide=$('#guide');guide.setAttribute('x1',xx);guide.setAttribute('x2',xx);guide.setAttribute('visibility','visible');const tip=$('#tooltip');tip.replaceChildren();const title=document.createElement('div');title.className='date';title.textContent=dateFmt.format(Date.parse(p.date));tip.append(title);const i=data.points.indexOf(p);for(const g of data.groups){if(!visible.has(g.id))continue;for(const[id,n]of layers()){const v=n===1?p.groups[g.id]?.value:average(data.points,g.id,n)[i];const row=document.createElement('div');row.className='row';const label=document.createElement('span');label.className='label';const sw=document.createElement('span');sw.className='swatch';sw.style.background=g.color;label.append(sw,document.createTextNode(g.label+(n===1?'':` · Ø ${n}`)));const value=document.createElement('span');value.textContent=num(v);row.append(label,value);tip.append(row);}}
 // Compact matrix keeps all selected averages readable on small screens.
 tip.querySelectorAll('.row').forEach(r=>r.remove());
 const table=document.createElement('table');table.className='tooltip-table';const head=document.createElement('tr');
 for(const title of ['Gruppe',...layers().map(([,n])=>n===1?'Tag':`Ø ${n}`)]){const th=document.createElement('th');th.textContent=title;head.append(th);}table.append(head);
 for(const g of data.groups){if(!visible.has(g.id))continue;const row=document.createElement('tr'),label=document.createElement('td');label.style.color=g.color;label.textContent=g.label;row.append(label);for(const[,n]of layers()){const td=document.createElement('td');td.textContent=num(n===1?p.groups[g.id]?.value:average(data.points,g.id,n)[i]);row.append(td);}table.append(row);}tip.append(table);
 const note=document.createElement('div');note.className='note';note.textContent=p.mode==='reconstructed'?'Rekonstruktion · heutige Gruppen':'Gespeicherte Tagesbeobachtung';tip.append(note);for(const g of data.groups){if(visible.has(g.id)){const q=p.groups[g.id];const n=document.createElement('div');n.className='note';n.textContent=`${g.label}: ${q.winners}/${q.eligible} besser · ${q.total-q.eligible} ohne Daten`;tip.append(n);}}
 tip.hidden=false;tip.style.left=Math.max(0,Math.min(geometry.w-tip.offsetWidth,xx+18))+'px';tip.style.top=Math.max(0,Math.min(geometry.h-tip.offsetHeight,event.clientY-rect.top-30))+'px';
}
svg.addEventListener('pointerdown',e=>{if(!data)return;drag={x:e.clientX,lo,hi,moved:false};svg.setPointerCapture(e.pointerId);inspect(e);});svg.addEventListener('pointermove',e=>{if(drag&&Math.abs(e.clientX-drag.x)>4){drag.moved=true;const delta=Math.round((e.clientX-drag.x)/geometry.W*(drag.hi-drag.lo)/DAY)*DAY;const min=Date.parse(data.points[0].date),max=Date.parse(data.latestDate);const shift=Math.max(drag.hi-max,Math.min(drag.lo-min,delta));lo=drag.lo-shift;hi=drag.hi-shift;activePeriod=null;render();}else if(!drag?.moved)inspect(e);});svg.addEventListener('pointerup',()=>drag=null);svg.addEventListener('pointercancel',()=>drag=null);svg.addEventListener('pointerleave',()=>{if(!drag){$('#tooltip').hidden=true;$('#guide')?.setAttribute('visibility','hidden');}});
svg.addEventListener('wheel',e=>{if(!data)return;e.preventDefault();const full=Date.parse(data.latestDate)-Date.parse(data.points[0].date);const newSpan=Math.max(Math.min(6*DAY,full),Math.min(full,(hi-lo)*(e.deltaY>0?1.25:.8)));const frac=Math.max(0,Math.min(1,(e.clientX-svg.getBoundingClientRect().left-geometry.L)/geometry.W));const center=lo+frac*(hi-lo);lo=Math.round((center-frac*newSpan)/DAY)*DAY;hi=lo+Math.round(newSpan/DAY)*DAY;activePeriod=null;render();},{passive:false});
for(const id of ['raw','sma7','sma14'])$('#'+id).addEventListener('change',render);$('#periods').addEventListener('click',e=>{if(data&&e.target.dataset.days)setPeriod(e.target.dataset.days);});$('#reset').onclick=()=>data&&setPeriod('ytd');for(const id of ['from','to'])$('#'+id).onchange=()=>{if(!data)return;const t=Date.parse($('#'+id).value);if(!Number.isFinite(t))return;if(id==='from')lo=Math.min(t,hi);else hi=Math.max(t,lo);activePeriod=null;render();};
async function load(){try{$('#refresh').disabled=true;const r=await fetch('data.json',{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const next=await r.json();if(!next.points?.length)throw Error('Noch keine Tageswerte');const initial=!data;data=next;if(initial){visible=new Set(data.groups.map(g=>g.id));for(const g of data.groups){const b=document.createElement('button');b.type='button';b.setAttribute('aria-pressed','true');const dot=document.createElement('span');dot.className='swatch';dot.style.background=g.color;b.append(dot,document.createTextNode(g.label));b.onclick=()=>{visible.has(g.id)?visible.delete(g.id):visible.add(g.id);b.setAttribute('aria-pressed',String(visible.has(g.id)));render();};$('#legend').append(b);}}
 const age=Date.now()-Date.parse(data.latestDate);$('#freshness').classList.toggle('stale',age>2*DAY);$('#freshness').textContent=(age>2*DAY?'Veralteter Stand · ':'Stand · ')+dateFmt.format(Date.parse(data.latestDate));$('#updated').textContent=`CoinGecko · Abruf ${new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Berlin'}).format(new Date(data.updatedAt))} (Berlin)`;
 $('#coinRows').replaceChildren();const coins=data.membership[data.latestDate]||[];for(const c of coins){const tr=document.createElement('tr');for(const value of [c.rank,`${c.name} (${c.symbol.toUpperCase()})`,data.groups.find(g=>c.rank>g.start&&c.rank<=g.end)?.label,new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}).format(c.marketCap)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}$('#coinRows').append(tr);}for(const id of ['from','to']){$('#'+id).min=data.points[0].date;$('#'+id).max=data.latestDate;}if(initial||activePeriod)setPeriod(activePeriod||'ytd');else render();
 }catch(e){$('#freshness').textContent=data?'Abruf fehlgeschlagen · alter Datenstand':'Daten noch nicht verfügbar';$('#freshness').classList.add('stale');if(!data){$('#empty').hidden=false;$('#empty').textContent='Die erste Datenberechnung ist noch nicht abgeschlossen. Bitte später neu laden.';$('#notice').textContent='Es werden keine Beispieldaten oder geschätzten Kurven angezeigt.';}console.error('Data load failed:',e.message);}finally{$('#refresh').disabled=false;}}
$('#refresh').onclick=load;new ResizeObserver(render).observe($('#chartWrap'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});setInterval(load,15*60*1000);load();
